Repository Team-Saisiot/portable-trackpad-client, pull requests merged in 2022-10, with the labels that each got.

#2 [2022.10.15] Main Screen 레이아웃 완성
  App.js
  package-lock.json
  package.json
  src/screen/MainScreen.js
Labels: Feature, Layout

#3 [2022.10.16] Login Screen 레이아웃 완성
  App.js
  package-lock.json
  package.json
  src/screen/LoginScreen.js
  src/screen/MainScreen.js
Labels: Layout

#5 [2022.10.17] 로그아웃 구현 완료
  package-lock.json
  package.json
  src/screen/LoginScreen.js
Labels: Feature

#7 [2022.10.19] 네트워크 연결 안내페이지 layout 완성
  App.js
  src/screen/DesktopAppDownloadScreen.js
  src/screen/NetworkGuideScreen.js
Labels: Feature, Layout

#9 [2022.10.19] TouchPad 페이지 layout 완성
  App.js
  package.json
  src/screen/DownloadGuideScreen.js
  src/screen/LoginScreen.js
  src/screen/MainScreen.js
  src/screen/NetworkGuideScreen.js
  src/screen/PcListScreen.js
  src/screen/TouchPadScreen.js
Labels: Feature, Layout

#10 [2022.10.20] Gesture 기본기능 구현 - Click
  app.json
  package-lock.json
  package.json
  src/screen/MainScreen.js
  src/screen/PcListScreen.js
  src/screen/TouchPadScreen.js
Labels: Feature

#12 [2022.10.20] Gesture 기본기능 구현 - Drag
  App.js
  package-lock.json
  package.json
  src/screen/DownloadGuideScreen.js
  src/screen/NetworkGuideScreen.js
  src/screen/PcListScreen.js
  src/screen/TouchPadScreen.js
Labels: Feature

#15 [2022.10.20] Gesture 기본기능 구현 - 브라우저 앞,뒤 이동
  src/screen/TouchPadScreen.js
Labels: Feature

#18 [2022.10.23] 제스처 모드 도입 및 제스처로 그리기 기능 구현
  package-lock.json
  package.json
  src/constants/colors.js
  src/screen/DownloadGuideScreen.js
  src/screen/LoginScreen.js
  src/screen/MainScreen.js
  src/screen/NetworkGuideScreen.js
  src/screen/PcListScreen.js
  src/screen/TouchPadScreen.js
Labels: Feature
